# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fVt-SolHwaRNHlSrFstOx87VGLFzoCq8
"""

n1 = int(input())
n2 = float(input())
n3 = float(input())

print("Primeiro numero =", n1)
print(f"{n2:.2f} eh o segundo numero")
print(f"Finalmente {n3:.3f} eh o terceiro numero")