# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fVt-SolHwaRNHlSrFstOx87VGLFzoCq8
"""

print("Alo, mundo!")