# -*- coding: utf-8 -*-
"""funcao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fVt-SolHwaRNHlSrFstOx87VGLFzoCq8
"""

def calcular_distancia(x1, y1, x2, y2):
  x = ((x2 - x1)**2)**0.5
  y = ((y2 - y1)**2)**0.5
  dist = int(x+y)
  return dist

calcular_distancia(2,3,3,4)