# -*- coding: utf-8 -*-
"""funcao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fVt-SolHwaRNHlSrFstOx87VGLFzoCq8
"""

x1  = float(input())
y1  = float(input())
x2  = float(input())
y2  = float(input())

x = ((x2 - x1)**2)
y = ((y2 - y1)**2)
dist = x+y
print(round(dist**0.5,2))